### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by justinalsing** [marius311/pypico#9]
When I try and run pypico on my laptop it always fails with (code at the bottom),

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

When I run the same lines of code on my desktop it works fine. Have you come across this - any idea what's behind it?

Thanks,
Justin

pico = pypico.load_pico("pico3_tailmonty_v34.dat")
outputs = ['cl_TT']
inputs = pico.example_inputs()
cls = pico.get(outputs, **inputs)

**Comment by marius311** [comment]
Hi Justin, can you first double check you have PICO installed from the master branch of this repo (rather than from PIP)?

**Comment by justinalsing** [comment]
Hi Marius - Yep I tried both. On my desktop it works (I think with pip I don’t remember) but on my laptop it works with neither. Both running mac…

Thanks!
Justin

**Comment by marius311** [comment]
Can you show the full stack trace? 

Also, what versions of Python and Numpy do you have running on these systems?

**Comment by justinalsing** [comment]
Hi Marius - 

On my laptop (the problem case) I am running

Python 2.7.12
Numpy 1.13.3

And I’m reading in the file “pico3_tailmonty_v34.dat” downloaded from the link on the github (which works fine on the desktop too)

Here’s what I get…

Thanks!

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-470fb38d7da1> in <module>()
      1 outputs = ['cl_TT']
      2 inputs = pico.example_inputs()
----> 3 cls = pico.get(outputs, **inputs)['cl_TT'][:]
      4 #l = np.arange(2, 5628)
      5 #cl = result['cl_TT']

<string> in get(self, outputs, force, **inputs)

<string> in get_result(self, inputs, derive, force)

<string> in xoutputs_to_outputs(self, xoutputs, allinputs)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by marius311** [comment]
Looks like the problem a change in how Numpy handles comparison to `None` in 1.13. 

Until I can fix PICO, you could try installing Numpy 1.12 as a workaround (`pip install numpy==1.12.0`).

**Comment by justinalsing** [comment]
Wonderful - great investigative work, that did the trick (and I never would have figured that out alone...)

Thanks so much! If we bump into each other, I definitely owe you a beer!

Thanks again :)
Justin

**Comment by marius311** [comment]
Glad I could help, really wasn't a lot of work for a beer, but I wouldn't say no :)

**Comment by marius311** [comment]
As of https://github.com/marius311/pypico/releases/tag/4.0.0 and the associated Python 3 data file in https://github.com/marius311/pypico-trainer/releases this should now work with the latest Numpy.
